name=LightAir
version=0.0.1
author=Rev <lightairgame@gmail.com>
maintainer=Rev <lightairgame@gmail.com>
sentence=A library for LightAir tag game
paragraph=Core and games to play with and develop LightAir
category=Device Control
url=http://light-air.it/
architectures=esp32
includes=WebServer.h
depends=
