#!/usr/bin/env python3
"""Generate src/lua/LightAir_GamesBundle.h from games/**.lua.

The bundle seeds LittleFS on first boot (and whenever the on-flash
copy differs byte-for-byte from the embedded one — see
LightAir_GameStore::seedDefaults) so a freshly flashed device has the
stock games without needing the HTTP upload path.  Run from the
repository root:

    python3 tools/embed_games.py

Commit the regenerated header together with game file changes.
"""

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "lua" / "LightAir_GamesBundle.h"

files = sorted(ROOT.glob("games/*.lua")) + sorted(ROOT.glob("games/lib/*.lua"))

def c_bytes(data: bytes, indent: str) -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)

parts = [
    "// AUTO-GENERATED by tools/embed_games.py — do not edit.",
    "// Stock game files embedded in the firmware; LightAir_GameStore",
    "// seeds them into LittleFS when missing or out of date.",
    "#pragma once",
    "#include <stddef.h>",
    "",
    "struct EmbeddedGameFile {",
    "    const char*          path;   // LittleFS destination",
    "    const unsigned char* data;",
    "    size_t               len;",
    "};",
    "",
]

names = []
for idx, f in enumerate(files):
    rel = "/" + f.relative_to(ROOT).as_posix()  # /games/foo.lua
    data = f.read_bytes()
    name = f"kGameFile{idx}"
    names.append((name, rel, len(data)))
    parts.append(f"// {rel} ({len(data)} bytes)")
    parts.append(f"static const unsigned char {name}[] = {{")
    parts.append(c_bytes(data, "    "))
    parts.append("};")
    parts.append("")

parts.append("static const EmbeddedGameFile kEmbeddedGames[] = {")
for name, rel, n in names:
    parts.append(f'    {{ "{rel}", {name}, {n} }},')
parts.append("};")
parts.append("")

OUT.write_text("\n".join(parts))
print(f"wrote {OUT} ({len(files)} files, {sum(n for _, _, n in names)} bytes)")
