name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v2.0.0
    - name: Setup SWIG
      uses: mmomtchev/setup-swig@v3
    - name: Build with Make
      run: make ./build/debug/LightAir.ino.bin
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug
        path: ./build/debug/LightAir.ino.bin
        if-no-files-found: error
        retention-days: 1

